---

- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: install ntp, ntpdate, upstart, monit, logrotate, nginx, git
  apt: pkg={{item}} state=latest
  with_items:
    - tlsdate
    - upstart
    - monit
    - logrotate
    - nginx
    - git-core

- name: be sure tlsdate is running
  service: name=tlsdate state=running

